### PR TITLE
version2.0rc1

### PR DESCRIPTION
**Pull request by genomematt**
Major rewrite and redesign of logic to accomodate working with groups of alignments for the same reads.

### CODE REVIEW

**Comment by afrubin** [comment]
I see all the tests have passed, but it would be good to see the coverage stats. It looks like Coveralls isn't turned on for this repo. Can we get this fixed and added to the PR checks?

**Comment by genomematt** [comment]
I have re-run the Travis tests and coverage is now both reported and required to pass for merge

**Comment by afrubin** [comment]
Needs a `# pragma: no cover` on the uncovered line in cli.py and then should be good to go.

**Comment by genomematt** [comment]
Ok, pragma fixed now

**Review by afrubin — APPROVED** [review]
Happy to approve seeing that all tests pass with 100% coverage.

**Review by jbedo — COMMENTED** [review]
There are a significant number of files that look like build products not source (_build, _source, . These shouldn't be part of the repository.

The binary blobs are also questionable as to whether they should be in git directly. Consider using LFS, which github supports.

**Comment by afrubin** [comment]
> There are a significant number of files that look like build products not source (_build, _source, . These shouldn't be part of the repository.

This is a good catch. The repository lacks a .gitignore. Consider adding GitHub's default Python .gitignore template, which will catch things like the Sphinx _build directory.

**Comment by genomematt** [comment]
Build products removed from repo.
Will consider blobs at a later date. They are relatively small so not a priority ATM.
A better solution will be required for example data and extended test data down the track and I am undecided on best option.

**Comment by genomematt** [comment]
I have also turned off Travis-CI.com as both Travis-CI.com and Travis-CI.org were running tests

**Comment by afrubin** [comment]
> I have also turned off Travis-CI.com as both Travis-CI.com and Travis-CI.org were running tests

You should turn off Travis-CI.org instead. See: https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-user-accounts

**Pull request merged**
